// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb4KAqogfY_e5jjhF5hwoYXUxYfp14hhs',
    appId: '1:22688897801:web:5ea312db6ad1bab05411d8',
    messagingSenderId: '22688897801',
    projectId: 'cloninginstagram-41dca',
    authDomain: 'cloninginstagram-41dca.firebaseapp.com',
    storageBucket: 'cloninginstagram-41dca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ_BNnspBGiG1JGbsVuCIR_ofau-uuC8Q',
    appId: '1:22688897801:android:e5515d46c8196e485411d8',
    messagingSenderId: '22688897801',
    projectId: 'cloninginstagram-41dca',
    storageBucket: 'cloninginstagram-41dca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk8daIY5DXID1j4zZbNmKtmxMpZ9eb0ig',
    appId: '1:22688897801:ios:4d404fec8c5c773d5411d8',
    messagingSenderId: '22688897801',
    projectId: 'cloninginstagram-41dca',
    storageBucket: 'cloninginstagram-41dca.appspot.com',
    iosClientId: '22688897801-5oirat5850hcikt8gebtdho4qu568nf3.apps.googleusercontent.com',
    iosBundleId: 'com.companyname.projectname',
  );
}
